export const SAVE_MARKER = "SAVE_MARKER";
export const PREPARE_NEW_MARKER = "PREPARE_NEW_MARKER";
export const UNSELECT_NEW_MARKER = "UNSELECT_NEW_MARKER";
export const PREVIEW_EXISTING_MARKER = "PREVIEW_EXISTING_MARKER";
export const EXIT_PREVIEW = "EXIT_PREVIEW";
